FactorinMaoc/maoc.Web/Controllers/EmpresaController.cs
using maoc.Funcionalidades;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace maoc.Web.Controllers
{
    public class EmpresaController : Controller
    {
        // GET: Empresa
        public ActionResult Lista(string userId)
        {
            //int idUser = 11;
            var Listado = new ListadoEmpresaHandler();
            return View(Listado.Listado(userId));
        }
        [HttpGet]
        public ActionResult Registrar(string userId)
        {
            return View(new CrearEmpresaViewModel());
        }

        [HttpPost]
        public ActionResult Registrar(string userId, CrearEmpresaViewModel modelo)
        {
            try
            {
                var CreaEmpresa = new CrearEmpresaHandler();
                modelo.NomUser = userId;
                CreaEmpresa.Ejecutar(modelo);
                return RedirectToAction("Lista",new { UserId = modelo.NomUser });
            }
            catch
            {
                return View();
            }
        }
    }
}

FactorinMaoc/maoc.Web/Controllers/FacturaController.cs
using maoc.Funcionalidades;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace maoc.Web.Controllers
{
    public class FacturaController : Controller
    {
        // GET: Factura
        public ActionResult Lista(int idEmpresax)
        {
            var Listado = new ListarFacturaHandler();
            return View(Listado.Listado(idEmpresax));
        }
    }
}

FactorinMaoc/maoc.Web/Views/Empresa/Lista.cshtml
@model IEnumerable<maoc.Funcionalidades.ListadoEmpresaViewModel>

@{
    ViewBag.Title = "Lista";
}

<h2>Empresas</h2>

<p>
    @Html.ActionLink("Nueva Empresa", "Registrar",new { userId = @Html.Value("userId") })
</p>
<p>
    @Html.Value("userId")
</p>
<table class="table">
    <tr>
       
        <th>
            @Html.DisplayNameFor(model => model.IdEmpresa)
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.IdUsuario)*@
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RUC)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Razon)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ubicacion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Rubro)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.IdEmpresa)
        </td>
        <td>
            @*@Html.DisplayFor(modelItem => item.IdUsuario)*@
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RUC)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Razon)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Ubicacion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Rubro)
        </td>
        <td valign="top" >
             <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle"
                           data-toggle="dropdown"
                           role="button"
                           aria-haspopup="true"
                           aria-expanded="false">Acciones<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Editar", "Editar", new { id = item.IdEmpresa })</li>
                            <li>@Html.ActionLink("Eliminar", "Eliminar", new { id = item.IdEmpresa })</li>
                            <li role="separator" class="divider"></li>
                            <li>@Html.ActionLink("ListadoFactura","Lista", "Factura", new { idEmpresax = item.IdEmpresa })</li>
                        </ul>
                     </li>
                    </ul>
                </div>

        </td>
    </tr>
}

</table>

FactorinMaoc/maoc.Web/Views/Empresa/Registrar.cshtml
@using Microsoft.AspNet.Identity
@model maoc.Funcionalidades.CrearEmpresaViewModel

@{
    ViewBag.Title = "Registrar Nueva Empresa";
}

<h2>Registrar</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>@Html.Value("userId")</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="form-group">
            @Html.LabelFor(model => model.IdEmpresa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdEmpresa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdEmpresa, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @*<div class="form-group">
            @Html.LabelFor(model => model.IdUsuario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
            
                   @Html.LabelFor(User.Identity.GetUserId(), htmlAttributes: new { @class = "control-label col-md-2" })

                   @Html.EditorFor(model => model.IdUsuario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdUsuario, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.RUC, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RUC, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RUC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Razon, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Razon, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Razon, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Departamento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Departamento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Departamento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Provincia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Provincia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Provincia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Distrito, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Distrito, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Distrito, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rubro, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rubro, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rubro, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Lista de Empresas", "Lista",new {userId=Html.Value("userId")})
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}